// <copyright file="OrderItem.cs" company="WavePoint Co. Ltd.">
// Licensed under the MIT license. See LICENSE file in the samples root for full license information.
// </copyright>

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace OnlineSales.Entities;

public class OrderItem : BaseEntity
{
    /// <summary>
    /// Gets or sets reference to Order table.
    /// </summary>
    [Required]
    public int OrderId { get; set; }

    [JsonIgnore]
    [ForeignKey("OrderId")]
    public virtual Order? Customer { get; set; }

    /// <summary>
    /// Gets or sets the name of the product as defined by vendor.
    /// </summary>
    [Required]
    public string ProductName { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets license code generated by the vendor.
    /// </summary>
    [Required]
    public string LicenseCode { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets total amount converted to a system currency (or payout currency) like USD without TAXes, discounts and comissions (how much will be paid out to vendor).
    /// </summary>
    [Required]
    public decimal Total { get; set; } = 0;

    /// <summary>
    /// Gets or sets the currency ISO code for the payment - ISO 4217. Example: "USD".
    /// </summary>
    [Required]
    public string Currency { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets total amount in the payment currency without TAXes, discounts and comissions (how much will be paid out to vendor).
    /// </summary>
    [Required]
    public decimal CurrencyTotal { get; set; } = 0;

    /// <summary>
    /// Gets or sets total amount of all items in the current order.
    /// </summary>
    public int Quantity { get; set; }
}
