// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using OnlineSales.Plugin.TestPlugin.TestData;

#nullable disable

namespace OnlineSales.Plugin.TestPlugin.Migrations
{
    /// <inheritdoc />
    public partial class UpdateDataTest : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
#pragma warning disable SA1118

            for (int i = 0; i < ChangeLogMigrationsTestData.InsertionData.Count(); i++)
            {
                migrationBuilder.UpdateData(
                    keyColumn: "id",
                    keyValue: i+1,
                    table: "test_entity",
                    column: "string_field",    
                    value: ChangeLogMigrationsTestData.InsertionData[i] + "Updated");
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // not needed
        }
    }
}
