// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using OnlineSales.Plugin.TestPlugin.TestData;

#nullable disable

namespace OnlineSales.Plugin.TestPlugin.Migrations
{
    /// <inheritdoc />
    public partial class AddColumnTest : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: ChangeLogMigrationsTestData.AddedColumnName,
                table: "test_entity",
                type: "integer",
                nullable: false,
                defaultValue: ChangeLogMigrationsTestData.AddedColumnDefaultValue);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // not needed
        }
    }
}
